### ISSUE TITLE
Gradle warnings

### ISSUE THREAD

**Issue by akaessens** [akaessens/NoFbEventScraper#14]
- [x] Fix linting warnings
- [x] remove deprecated gradle options for 7.0

**Comment by akaessens** [comment]
https://github.com/gradle/gradle/issues/14236 for deprecated warning

**Comment by akaessens** [comment]
F-Droid's buildserver explicitly checks the gradle hash. The latest gradle versions are not supported yet, see: 
https://f-droid.org/wiki/page/com.termux/lastbuild_99. As of now the [buildserver accepts up to gradle 6.5 ](https://gitlab.com/fdroid/fdroidserver/-/blob/e659a5353dea91bf964585c68bf35a9314ec0656/gradlew-fdroid) and this is fortunately also currently used in this app.

**Comment by 6543** [comment]
https://f-droid.org/wiki/page/com.akdev.nofbeventscraper/lastbuild_7 <- Build succeeded

but it is a good idear to prepare for 7.0 👍
