### ISSUE TITLE
Submit to FDroid

### ISSUE THREAD

**Issue by akaessens** [akaessens/NoFbEventScraper#2]
New releases shall be done via FDroid

- [x] Add MR to fdroiddata -  [fdroid/fdroiddata!6823](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/6823)
- [x] Add request for packaging - [fdroid/rfp#1354](https://gitlab.com/fdroid/rfp/-/issues/1354)
- [x] wait for feedback or packaging
- [x] update downloads section in readme
- [x] point changelog and download in-app to fdroid

**Comment by 6543** [comment]
@akaessens I think it's time to add the FDroid lable ;)

**Comment by akaessens** [comment]
Hi, @6543, thanks for engaging on my MR :) 
I will update as soon as the build is ready: I expect it at https://f-droid.org/en/packages/com.akdev.nofbeventscraper

**Comment by 6543** [comment]
@akaessens https://f-droid.org/en/packages/com.akdev.nofbeventscraper :tada:

**Comment by akaessens** [comment]
> @akaessens https://f-droid.org/en/packages/com.akdev.nofbeventscraper tada

yes! just saw it, too!

**Comment by TPS** [comment]
@akaessens Problem: this got newly published directly to the F-droid _Archive_!

@IzzySoft Who does 1 contact specifically re: such a mis-published new app?

**Comment by IzzySoft** [comment]
@TPS see https://gitlab.com/fdroid/fdroidserver/-/merge_requests/771/diffs?commit_id=a656be82ae259c38607105ccfabd7f89c78506d8 (known issue, already solved, fix just not yet deployed).

**Comment by TPS** [comment]
@IzzySoft Whenever it _is_ deployed, do you know whether the fix you pointed to means that all apps with this problem will be retroactively fixed, wait 'til next release of each, or something else?

**Comment by IzzySoft** [comment]
Looking at the linked diff I'd answer that with a "yes": those parts are not from building the app, but from creating the index – and thus dealing with each APK available (built just now or 5 years ago doesn't matter). So it should be "retroactively". I've no idea though why this only affected "selected apps" – or what made it happen to exactly those it happened to but not to others. Not worth digging into that, now the issue should be fixed. We just need to wait for it to be deployed.

**Comment by TPS** [comment]
@IzzySoft & _now_ everything's fine on the index (e.g., _this_ app is published correctly).

@akaessens Close FTW? 🙇🏾‍♂️

**Comment by IzzySoft** [comment]
Uh? OK, I wasn't aware the fix was deployed, or a new index published – but if you say so :wink:

**Comment by akaessens** [comment]
> @IzzySoft & _now_ everything's fine on the index (e.g., _this_ app is published correctly).
> 
> @akaessens Close FTW? 🙇🏾‍♂️

Alright @TPS @IzzySoft , i'm closing this then :) 
thank you very much!
