### ISSUE TITLE
A display issue

### ISSUE THREAD

**Issue by franklinbill** [akaessens/NoFbEventScraper#27]
Dear developer!
In the process of using, I found a bug in layout / display. As shown in the figure, in the about page, the image disappears. This may be an adaptation problem. I suspect it is because **display and font size** are set to large (mainly due to **display size**).
I hope that the page can be set to scroll, so that the problem caused by the display size of large can be solved.
App version is  1.5.8 , my mobile phone is Google nexus 6, screen resolution setting is 1920* 1080, **_font size and display size are the largest ! ! !_**, Android system is 8.0.
The above is a description of the problem. The overall experience of the software is good. You can see that the design is very attentive. Thank you very much for the efforts of the developers all the time. I hope to receive a reply.
Thank you!
<img width="445" alt="bug-nofbevebtscraper" src="https://user-images.githubusercontent.com/18572115/103148231-8b252300-4798-11eb-9d5d-3e81279ceb14.png">

**Comment by akaessens** [comment]
Hi, that's probably because you have no internet. The image is loaded from github. But it's just the PayPal image with the same URL like the PayPal text hyperlink, so nothing important.

Thanks for testing and let me know if you encounter other things!

**Comment by franklinbill** [comment]
Thanks for your reply!
